# Generated by Django 3.2 on 2023-08-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='original',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.IntegerField()),
                ('merchant', models.IntegerField()),
                ('country', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=4)),
                ('currency', models.CharField(max_length=60)),
            ],
        ),
    ]
