# Generated by Django 3.2 on 2023-08-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original',
            name='trans_id',
            field=models.CharField(max_length=60),
        ),
    ]
