# Generated by Django 3.2 on 2023-08-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_original_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original',
            name='amount',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
